<?php

/**
 * @file
 * Module file for the unocha_users module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\user\RoleInterface;

/**
 * Implements hook_form_user_form_alter().
 */
function unocha_users_form_user_form_alter(array &$form, FormStateInterface $form_state) {
  $current_user = \Drupal::currentUser();
  $same_user = $current_user->id() === $form_state->getFormObject()->getEntity()->id();

  // Disable access to fields if not on own form and no permission to edit them.
  if (!$same_user && !$current_user->hasPermission('edit other user account details')) {
    $form['account']['mail']['#access'] = FALSE;
    $form['account']['name']['#access'] = FALSE;
    $form['account']['pass']['#access'] = FALSE;
    $form['account']['notify']['#access'] = FALSE;

    $form['contact']['#access'] = FALSE;
    $form['display_name']['#access'] = FALSE;
    $form['language']['#access'] = FALSE;
    $form['timezone']['#access'] = FALSE;
  }

  // Disable option to cancel account without proper permission.
  if (!$same_user && !$current_user->hasPermission('block other user account')) {
    $form['account']['status']['#access'] = FALSE;
  }

  // Disable option to cancel account without proper permission.
  if (!$same_user && !$current_user->hasPermission('cancel other user account')) {
    $form['actions']['delete']['#access'] = FALSE;
  }

  // Check if the user is allowed to assign roles.
  if ($current_user->hasPermission('manage other user acount roles') && !empty($form['account']['roles']['#options'])) {
    $form['account']['roles']['#access'] = TRUE;

    $default_roles = $form['account']['roles']['#default_value'] ?? [];

    foreach ($form['account']['roles']['#options'] as $role => $label) {
      if ($role === RoleInterface::ANONYMOUS_ID) {
        continue;
      }
      // No need to display the authenticated role.
      elseif ($role === RoleInterface::AUTHENTICATED_ID) {
        $form['account']['roles'][$role]['#access'] = FALSE;
      }
      // Only display the roles that can be assigned by the current user.
      elseif (!$current_user->hasPermission('assign ' . $role . ' role')) {
        $form['account']['roles'][$role]['#access'] = FALSE;
        $form['account']['roles'][$role]['#disabled'] = TRUE;
        $form['account']['roles'][$role]['#default_value'] = in_array($role, $default_roles);
      }
    }
  }
  else {
    $form['account']['roles']['#access'] = FALSE;
  }
}
