unocha_figures.settings:
  type: config_object
  label: 'UNOCHA Figures settings'
  mapping:
    ocha_key_figures_api_url:
      type: string
      label: 'OCHA Key Figures API URL'
    ocha_key_figures_api_key:
      type: string
      label: 'API Key for the OCHA Key Figures API'
    ocha_key_figures_api_appname:
      type: string
      label: 'App name parameter to indentify the API requests.'
    ocha_key_figures_api_cache_enabled:
      type: boolean
      label: 'Cache the API query results.'
    ocha_key_figures_api_cache_lifetime:
      type: integer
      label: 'How long to cache the API query results.'
    ocha_key_figures_api_verify_ssl:
      type: boolean
      label: 'Verify the SSL certificate of the API query performing requests.'

field.field_settings.key_figure:
  type: mapping
  mapping:
    label:
      type: string
      label: 'Figure label'
    value:
      type: string
      label: 'Figure value'
    unit:
      type: string
      label: 'Figure unit'
    provider:
      type: string
      label: 'Figure provider'
    id:
      type: string
      label: 'Figure ID'
    country:
      type: string
      label: 'Figure country'
    year:
      type: integer
      label: 'Figure year'
