<?php

/**
 * @file
 * Helper functions that applies to a variety of things on UNOCHA.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_preprocess().
 *
 * Ensure the attributes and *_attributes are set for the unocha templates.
 */
function unocha_utility_preprocess(array &$variables, $hook) {
  if (strpos($hook, 'unocha_') === 0) {
    foreach ($variables as $key => $value) {
      if ($key === 'attributes' || strpos($key, '_attributes') !== FALSE) {
        if (is_null($value)) {
          $variables[$key] = new Attribute();
        }
      }
    }
  }
}
