label: 等待审核的内容
description: 查找并审核内容。
display:
  default:
    display_title: 默认
    display_options:
      title: 等待审核的内容
      fields:
        title:
          label: 标题
          separator: ', '
        type:
          label: 内容类型
          separator: ', '
        name:
          label: 作者
          separator: ', '
        moderation_state:
          label: 审批状态
          separator: ', '
        changed:
          label: 已更新
          separator: ', '
        operations:
          label: 操作
      pager:
        options:
          tags:
            next: '下一个 ›'
            previous: '‹ 上一个'
            first: '« 首页'
            last: '末页 »'
          expose:
            items_per_page_label: 每页条目数
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 偏移量
      exposed_form:
        options:
          submit_button: 过滤
          reset_button_label: 重置
          exposed_sorts_label: 排序依据
          sort_asc_label: 升序
          sort_desc_label: 降序
      filters:
        title:
          expose:
            label: 标题
        type:
          expose:
            label: 内容类型
        moderation_state:
          expose:
            label: 审批状态
        langcode:
          expose:
            label: 语言
  moderated_content:
    display_title: 等待审核的内容
