_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_denied: 0
  allowed_formats: 0
  block: 0
  breakpoint: 0
  choices: 0
  ckeditor5: 0
  components: 0
  config: 0
  config_split: 0
  config_translation: 0
  contextual: 0
  csp: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  datetime_range_timezone: 0
  double_field: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  entity_usage: 0
  field: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  filter: 0
  geofield: 0
  google_tag: 0
  image: 0
  imageapi_optimize: 0
  imageapi_optimize_binaries: 0
  imageapi_optimize_webp: 0
  imageapi_optimize_webp_responsive: 0
  imagemagick: 0
  inline_form_errors: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  layout_paragraphs: 0
  link: 0
  linkit: 0
  locale: 0
  maintenance200: 0
  media: 0
  media_library: 0
  memcache: 0
  memcache_admin: 0
  menu_breadcrumb: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  ocha_key_figures: 0
  ocha_search: 0
  oembed_providers: 0
  options: 0
  page_cache: 0
  paragraph_view_mode: 0
  path: 0
  path_alias: 0
  redirect: 0
  responsive_image: 0
  serialization: 0
  social_api: 0
  social_auth: 0
  social_auth_hid: 0
  sophron: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  unocha_breadcrumbs: 0
  unocha_canto: 0
  unocha_donors: 0
  unocha_maps: 0
  unocha_menus: 0
  unocha_migrate: 0
  unocha_paragraphs: 0
  unocha_reliefweb: 0
  unocha_utility: 0
  update: 0
  user: 0
  user_display_name: 0
  user_expire: 0
  username_enumeration_prevention: 0
  verf: 0
  viewsreference: 0
  xmlsitemap_engines: 0
  pathauto: 1
  xmlsitemap: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stark: 0
  stable: 0
  common_design: 0
  common_design_subtheme: 0
  claro: 0
  common_design_claro: 0
profile: minimal
