_core:
  default_config_hash: yOPH6uEZYRHbg2OFP-bze0jGr06fI-Gr_66W-vA8Faw
report-only:
  enable: true
  directives:
    connect-src:
      base: self
      sources:
        - www.google-analytics.com
        - '*.analytics.google.com'
        - gov-bam.nr-data.net
    font-src:
      base: self
      sources:
        - 'data:'
        - fonts.gstatic.com
    img-src:
      base: self
      sources:
        - 'data:'
        - www.google-analytics.com
    object-src:
      base: none
    script-src:
      base: self
      flags:
        - unsafe-inline
      sources:
        - fonts.googleapis.com
        - www.gstatic.com
        - www.google.com
        - www.googletagmanager.com
        - cdn.jsdelivr.net
        - js-agent.newrelic.com
        - gov-bam.nr-data.net
        - '*.google-analytics.com'
    script-src-attr:
      base: self
    script-src-elem:
      base: self
      flags:
        - unsafe-inline
      sources:
        - fonts.googleapis.com
        - www.gstatic.com
        - www.google.com
        - www.googletagmanager.com
        - cdn.jsdelivr.net
        - js-agent.newrelic.com
        - gov-bam.nr-data.net
        - '*.google-analytics.com'
    style-src:
      base: self
      flags:
        - unsafe-inline
    style-src-attr:
      base: self
      flags:
        - unsafe-inline
    style-src-elem:
      base: self
      flags:
        - unsafe-inline
    frame-ancestors:
      base: self
  reporting:
    plugin: sitelog
enforce:
  enable: false
  directives:
    object-src:
      base: none
    frame-ancestors:
      base: self
  reporting:
    plugin: sitelog
