_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    ar: ar
    zh-hans: zh
    en: ''
    fr: fr
    es: es
    ru: ru
  domains:
    ar: ''
    zh-hans: ''
    en: ''
    fr: ''
    es: ''
    ru: ''
selected_langcode: site_default
