_core:
  default_config_hash: QYjt66qhIS8PVG3-ASm3Y28rmxl32szjFV6LCtDJP0k
endpoint_login: 'https://login.mediavalet.com'
endpoint_api: 'https://api.mediavalet.com'
username: ''
password: ''
subscription_key: ''
client_id: ''
secret: ''
