_core:
  default_config_hash: oDGEkhP0h5rXXqlDplxeBDre0goLigOJupHKMDMwcqM
login_menu_item_title: 'In Log'
logout_menu_item_title: 'Out Log'
login_redirect_url: ''
logout_redirect_url: ''
error_redirect_url: ''
error_throw: false
local_login_saml_error: false
logout_different_user: false
drupal_login_roles:
  authenticated: '0'
  administrator: '0'
  editor: '0'
sp_entity_id: ''
sp_name_id_format: ''
sp_x509_certificate: ''
sp_new_certificate: ''
sp_private_key: ''
metadata_valid_secs: 60
metadata_cache_http: false
idp_entity_id: ''
idp_single_sign_on_service: ''
idp_single_log_out_service: ''
idp_change_password_service: ''
idp_certs: ''
idp_cert_encryption: ''
unique_id_attribute: oid
map_users: false
map_users_name: false
map_users_mail: true
map_users_roles:
  administrator: administrator
  editor: editor
create_users: true
sync_name: true
sync_mail: true
user_name_attribute: name
user_mail_attribute: mail
request_set_name_id_policy: false
strict: true
security_metadata_sign: false
security_authn_requests_sign: false
security_logout_requests_sign: false
security_logout_responses_sign: false
security_nameid_encrypt: false
security_signature_algorithm: ''
security_encryption_algorithm: ''
security_messages_sign: false
security_assertions_signed: false
security_assertions_encrypt: false
security_nameid_encrypted: false
security_want_name_id: false
security_request_authn_context: false
security_lowercase_url_encoding: false
security_logout_reuse_sigs: false
security_allow_repeat_attribute_name: false
debug_display_error_details: false
debug_log_in: true
debug_log_saml_in: true
debug_log_saml_out: true
debug_phpsaml: false
use_proxy_headers: false
use_base_url: true
bypass_relay_state_check: false
