_core:
  default_config_hash: aDAuKinNUSmlWFFUTQRGt_8VoL0d8RUKNeYKlClzscw
client_id: CLIENT_ID
client_secret: SECRET
base_url: 'https://auth.humanitarian.id'
auto_redirect: true
disable_default: true
disable_password_fields: true
disable_email_field: false
disable_user_field: true
disable_user_create: true
maintenance_access: false
