_core:
  default_config_hash: 0E8z47ONguVcapiw1PGWDRs6g0NRDCzrym4mP_jcELU
auth:
  social_auth_hid:
    route: social_auth_hid.redirect_to_hid
    img_path: modules/contrib/social_auth_hid/img/hid_logo.png
post_login: /user
user_allowed: register
redirect_user_form: false
disable_admin_login: true
disabled_roles: {  }
