_core:
  default_config_hash: pH9IXcpNTu1DEHMft1YGjqy711f12t-Gq9lFuNIqyMQ
canto_api_url: 'https://unocha.canto.com/api/v1'
canto_api_app_id: null
canto_api_app_secret: null
canto_api_app_website: null
canto_api_cache_enabled: true
canto_api_cache_lifetime: 300
canto_api_verify_ssl: true
canto_oauth_domain_url: 'https://oauth.canto.com'
canto_site_base_url: 'https://unocha.canto.com'
