#!/bin/sh

# Lint php code.

# We only lint files from the custom themes and modules.
include='^html/(modules|themes)/custom/.*\.(php|module|inc|install|test|profile|theme|info|yml|twig)$'
exclude='(node_modules|vendor)'

# The linter path is relative to the root of the repository.
relative=1
linter="vendor/bin/phpcs"
options='-p --report=full --standard=phpcs.xml'
message='Linting staged PHP files (coding standards)...'

# Docksal compatibility.
if [ -x "$(command -v fin)" ]; then
  linter="phpcs"
fi

# Load and execute the linting code.
. "$(dirname "$0")/lint-common"
