#!/bin/sh

# Lint php code.

# We only lint files from the custom themes and modules.
include='^html/(modules|themes)/custom/.*\.(php|module|inc|install|test|profile|theme)$'
exclude='(node_modules|vendor)'

# Assume that the php command is global.
linter="php"
options='-l'
message='Linting staged PHP files (syntax)...'

# Load and execute the linting code.
. "$(dirname "$0")/lint-common"
