<?php

/**
 * @file
 * Module file for the ReliefWeb integration.
 */

/**
 * Implements hook_theme().
 */
function unocha_reliefweb_theme() {
  $themes = [
    // Theme for a ReliefWeb document.
    'unocha_reliefweb_document' => [
      'variables' => [
        // Heading level.
        'level' => 1,
        // Wrapper attributes.
        'attributes' => NULL,
        // Document title.
        'title' => NULL,
        // Attributes for the title.
        'title_attributes' => NULL,
        // Document publication date.
        'date' => NULL,
        // Document's main content.
        'content' => NULL,
        // Attributes for the content.
        'content_attributes' => NULL,
      ],
    ],
    // Theme for a list of attachments.
    'unocha_reliefweb_attachment_list' => [
      'variables' => [
        // Section heading level.
        'level' => 2,
        // Section attributes.
        'attributes' => NULL,
        // Section title.
        'title' => t('Attachments'),
        // Section title attributes.
        'title_attributes' => NULL,
        // List of files. Each item has the following properties:
        // - url: link to the file
        // - name: file name
        // - label: file name or 'Download' etc.
        // - description: file description (extension, size, language etc.)
        'list' => [],
        // List attributes.
        'list_attributes' => NULL,
        // Section footer.
        'footer' => NULL,
        // Section footer attributes.
        'footer_attributes' => NULL,
        // Flag to indicate if the first attachment's preview should be lazy
        // loaded or not.
        'lazy_load_first_preview' => TRUE,
      ],
    ],
  ];

  return $themes;
}
