<?php

/**
 * @file
 * Module file for the MediaValet integration.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\media\OEmbed\Provider;

/**
 * Implements hook_form_alter().
 */
function ocha_mediavalet_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  $form_ids = [
    'media_library_add_form_oembed',
    'media_library_add_form_upload',
    'media_library_extend_pane_form',
    'node_basic_edit_form',
    'node_basic_form',
    'node_event_edit_form',
    'node_event_form',
    'node_leader_edit_form',
    'node_leader_form',
    'node_media_collection_edit_form',
    'node_media_collection_form',
    'node_region_edit_form',
    'node_region_form',
    'node_resource_edit_form',
    'node_resource_form',
    'node_response_edit_form',
    'node_response_form',
    'node_story_edit_form',
    'node_story_form',
  ];

  // Preload libraries so switching panes does work.
  if (in_array($form_id, $form_ids)) {
    $form['#attached']['library'][] = 'media_library_extend/ui';
    $form['#attached']['library'][] = 'select_a11y/select_a11y.widget';
  }
}

/**
 * Implements hook_media_source_info_alter().
 */
function ocha_mediavalet_media_source_info_alter(array &$sources) {
  $sources['oembed:video']['providers'][] = 'MediaValet';
}

/**
 * Implements hook_oembed_resource_url_alter().
 */
function ocha_mediavalet_oembed_resource_url_alter(array &$parsed_url, Provider $provider) {
  // Rewrite the oembed endpoint to use the current host so that
  // it can work on local or development sites.
  if (strpos($parsed_url['path'], '/mediavalet/oembed') !== FALSE) {
    $oembed_base_url = \Drupal::config('ocha_mediavalet.settings')?->get('oembed_base_url');

    if (empty($oembed_base_url)) {
      $oembed_base_url = \Drupal::request()->getSchemeAndHttpHost();
    }

    $parsed_url['path'] = $oembed_base_url . '/mediavalet/oembed';
  }
}
