<?php

/**
 * @file
 * Module file for the MediaValet integration.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function ocha_mediavalet_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  // Preload libraries so switching panes does work.
  if (strpos($form_id, 'node_media_collection_form') === 0) {
    $form['#attached']['library'][] = 'media_library_extend/ui';
    $form['#attached']['library'][] = 'select_a11y/select_a11y.widget';
  }
}
