name: Run Composer Update with Scripts

on:
  schedule:
    - cron: '30 6 * * 4'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Update The Thing with scripts
      id: update-action-with-scripts
      uses: UN-OCHA/actions/composer-update@OPS-11381-scripts-flag
      with:
        aws_access_key_id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
        composer_scripts: "true"
        github_access_token: ${{ secrets.PAT }}
        patch_branch: ${{ github.head_ref || github.ref_name }}
        patch_maintainers: ${{ secrets.DRUPAL_MAINTAINERS }}
        slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack_channel_name: ${{ vars.SLACK_CHANNEL }}
