name: Build docker image

on:
  push:
    branches:
      - develop
      - 'feature/**'
      - main
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Build
      id: build-action
      uses: UN-OCHA/actions/drupal-docker-build@main
      with:
        aws_role: ${{ vars.AWS_ROLE }}
        aws_region: ${{ vars.AWS_REGION }}
        aws_account: ${{ vars.AWS_ACCOUNT }}
        docker_registry_url: public.ecr.aws
        docker_registry_path: /unocha/
        docker_image: unocha-site
        ecr_jenkins_token: ${{ secrets.JENKINS_ECR_TOKEN }}
        slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack_channel_name: ${{ vars.SLACK_CHANNEL }}
