name: Trigger auto deployment for unocha-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ feature/azure-app-ssh ]
    paths:
    - '**'
    - '.github/workflows/unocha-dev-AutoDeployTrigger-fef1a220-784d-49c4-a1a9-03652b61bf3f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.UNOCHADEV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.UNOCHADEV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.UNOCHADEV_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/docker
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ochalinuxprodsharedserviceacr.azurecr.io
          registryUsername: ${{ secrets.UNOCHADEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.UNOCHADEV_REGISTRY_PASSWORD }}
          containerAppName: unocha-dev
          resourceGroup: OCHA-Linux-Prod-SharedServices
          imageToBuild: ochalinuxprodsharedserviceacr.azurecr.io/unocha-dev:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


