<?php

/**
 * @file
 * Module file for the Canto integration.
 */

use Drupal\media\OEmbed\Provider;

/**
 * Implements hook_theme().
 */
function unocha_canto_theme() {
  $themes = [
    // Theme for a Canto portal.
    'unocha_canto_portal' => [
      'variables' => [
        // Wrapper attributes.
        'attributes' => NULL,
        // Content attributes.
        'content_attributes' => NULL,
        // URL of the canto portal.
        'url' => NULL,
      ],
    ],
  ];

  return $themes;
}

/**
 * Implements hook_media_source_info_alter().
 */
function unocha_canto_media_source_info_alter(array &$sources) {
  $sources['image']['forms']['media_library_add'] = '\Drupal\unocha_canto\Form\CantoImageForm';
  $sources['oembed:video']['forms']['media_library_add'] = '\Drupal\unocha_canto\Form\CantoVideoForm';
}

/**
 * Implements hook_oembed_resource_url_alter().
 */
function unocha_canto_oembed_resource_url_alter(array &$parsed_url, Provider $provider) {
  // Rewrite the UNOCHA Canto provider endpoint to use the current host so that
  // it can work on local or development sites.
  if (strpos($parsed_url['path'], '/canto/oembed') !== FALSE) {
    $parsed_url['path'] = \Drupal::request()->getSchemeAndHttpHost() . '/canto/oembed';
  }
}
